# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b54cc7ab91848f97eddc2131802ae95e03316e5cc1ffc0be2990cfeb9d04d4b1424b48e78b1de8a9e8f2b6d76c69d39dcbd4f23dc0733ad101a85c3b52d78896

test:
  secret_key_base: 2e90a118aac2ad2bb07c3802df5b10819ef5bd8b2b074035a9b485b7fdfc493e3d9dd1d462e02839a4605df9648313e6101a22506a795f149ec336ce719224ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
